### ISSUE TITLE
WS-Federation broken as of 1.5.10

### ISSUE THREAD

**Issue by tholabrk** [ironmansoftware/powershell-universal-legacy#104]
#### Description

WS-Federation stopped working when I upgraded to 1.5.13, I pretty quickly narrowed it down to be broken between 1.5.9 and 1.5.10, and it has been broken ever since.

The logs specify that it cannot find a specific cookie (.ASpNetcore.Correlation.<bunchofnumbersandletters>), but devtools does see the cookie...

Downgrading to 1.5.9 solves the issue, but no version between 1.5.10 and 1.5.13 works.

#### Additional Information

Stack-trace:
2021-03-04T14:18:00.7612583+01:00  [INF] Now listening on: "http://[::]:80" (d826f4b8)
2021-03-04T14:18:00.7613239+01:00  [INF] Now listening on: "https://[::]:443" (d826f4b8)
2021-03-04T14:18:00.7634035+01:00  [INF] Application started. Hosting environment: "Production"; Content root path: "C:\Program Files (x86)\Universal\" (9029d6f8)
2021-03-04T14:18:11.4875550+01:00 <privacy>:00000001 [INF] Request starting HTTP/2 POST https://<privacy>/auth/signin-wsfed application/x-www-form-urlencoded 6922 (ca22a1cb)
2021-03-04T14:18:11.8603958+01:00 <privacy>:00000001 [WRN] '".AspNetCore.Correlation.<privacy>"' cookie not found. (85986347)
2021-03-04T14:18:11.8606356+01:00 <privacy>:00000001 [INF] Error from RemoteAuthentication: "Correlation failed.". (37f74bc6)
2021-03-04T14:18:11.9511248+01:00 <privacy>:00000001 [ERR] Connection id ""<privacy>"", Request id ""<privacy>:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

#### Version Information

- Universal: 1.5.10-1.5.13
- Universal Hosting Method (IIS, Executable, docker etc): Executable
- PowerShell: Any
- Operating System: Any

**Comment by adamdriscoll** [comment]
This will be fixed in 1.5.14.

**Comment by adamdriscoll** [comment]
We've released 1.5.14. If the build resolves it for you, please close this issue.

**Comment by tholabrk** [comment]
That did indeed fix it 👍
